// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace StayInTarkov.FlatBuffers
{

public enum AnyPacket : byte
{
  NONE = 0,
  player_state = 1,
};


}
