// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace StayInTarkov.FlatBuffers
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct BodyPartHealth : IFlatbufferObject
{
  private Struct __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public void __init(int _i, ByteBuffer _bb) { __p = new Struct(_i, _bb); }
  public BodyPartHealth __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public float Current { get { return __p.bb.GetFloat(__p.bb_pos + 0); } }
  public float Maximum { get { return __p.bb.GetFloat(__p.bb_pos + 4); } }

  public static Offset<StayInTarkov.FlatBuffers.BodyPartHealth> CreateBodyPartHealth(FlatBufferBuilder builder, float Current, float Maximum) {
    builder.Prep(4, 8);
    builder.PutFloat(Maximum);
    builder.PutFloat(Current);
    return new Offset<StayInTarkov.FlatBuffers.BodyPartHealth>(builder.Offset);
  }
}


}
