// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace StayInTarkov.FlatBuffers
{

public enum EBodyPart : byte
{
  Head = 0,
  Chest = 1,
  Stomach = 2,
  LeftArm = 3,
  RightArm = 4,
  LeftLeg = 5,
  RightLeg = 6,
  Common = 7,
};


}
