// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace StayInTarkov.FlatBuffers
{

public enum EPlayerState : byte
{
  None = 0,
  Idle = 1,
  ProneIdle = 2,
  ProneMove = 3,
  Run = 4,
  Sprint = 5,
  Jump = 6,
  FallDown = 7,
  Transition = 8,
  BreachDoor = 9,
  Loot = 10,
  Pickup = 11,
  Open = 12,
  Close = 13,
  Unlock = 14,
  Sidestep = 15,
  DoorInteraction = 16,
  Approach = 17,
  Prone2Stand = 18,
  Transit2Prone = 19,
  Plant = 20,
  Stationary = 21,
  Roll = 22,
  JumpLanding = 23,
  ClimbOver = 24,
  ClimbUp = 25,
  VaultingFallDown = 26,
  VaultingLanding = 27,
  BlindFire = 28,
};


}
