name: SIT Build Release

on:
  push:
    paths-ignore:
      - '.github/*'
      - '.github/*_TEMPLATE/**'
      - '*.md'
  pull_request:
    paths-ignore:
      - '.github/*'
      - '.github/*_TEMPLATE/**'
      - '*.md'
  workflow_run:
    types:
      - completed
    workflows:
      - 'SIT CI'
  workflow_dispatch:
    paths-ignore:
      - '.github/*'
      - '.github/*_TEMPLATE/**'
      - '*.md'

permissions:
  contents: write

jobs:
  build:

    strategy:
      matrix:
        configuration: [Release]

    runs-on: ubuntu-latest

    env:
      SolutionName: StayInTarkov
      CSProj: Source/StayInTarkov.csproj

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Install .NET Core SDK
      - name: Install .NET Core SDK
        run: |
          sudo apt-get update
          sudo apt-get install -y dotnet-sdk-6.0

      # Restore all projects
      - name: dotnet Restore
        run: dotnet restore

      # Build the project
      - name: dotnet Publish
        run: |
          mkdir ${{ env.SolutionName }}-${{ matrix.configuration }}
          dotnet build ${{ env.CSProj }} -c ${{ matrix.configuration }} -o ${{ env.SolutionName }}-${{ matrix.configuration }}

      # Extract version number from StayInTarkov.dll
      - name: Get version from DLL
        id: extract-version
        run: |
          version=$(dotnet --version)
          echo "::set-output name=VERSION::$version"

      # Remove unnecessary files
      - name: Remove unnecessary files
        run: |
          rm ${{ env.SolutionName }}-${{ matrix.configuration }}/StayInTarkov.pdb

      # Zip remaining files
      - name: Zip remaining files
        run: |
          zip -r ${{ env.SolutionName }}-${{ matrix.configuration }}.zip ${{ env.SolutionName }}-${{ matrix.configuration }}

      # Upload artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: StayInTarkov-Client-${{ matrix.configuration }}-${{ steps.extract-version.outputs.VERSION }}
          path: ${{ env.SolutionName }}-${{ matrix.configuration }}/
          if-no-files-found: error

      # Create release as draft from the compressed file
      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: ${{ matrix.configuration == 'Release' }}
        with:
          draft: true
          generate_release_notes: true
          files: ${{ env.SolutionName }}-${{ matrix.configuration }}-${{ steps.extract-version.outputs.VERSION }}.zip
          tag_name: StayInTarkov.Client-${{ steps.extract-version.outputs.VERSION }}
