name: SIT Build Release Linux

on:
  push:
    paths-ignore:
      - '.github/*'
      - '.github/*_TEMPLATE/**'
      - '*.md'
  pull_request:
    paths-ignore:
      - '.github/*'
      - '.github/*_TEMPLATE/**'
      - '*.md'
  workflow_dispatch:
    paths-ignore:
      - '.github/*'
      - '.github/*_TEMPLATE/**'
      - '*.md'

permissions:
  contents: write

jobs:
  build:

    strategy:
      matrix:
        configuration: [Release]

    runs-on: ubuntu-latest

    env:
      SolutionName: StayInTarkov
      CSProj: Source/StayInTarkov.csproj

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: Dotnet Restore
        run: dotnet restore

      - name: Dotnet Publish
        run: |
          mkdir ${{ env.SolutionName }}-${{ matrix.configuration }}
          dotnet build ${{ env.CSProj }} -c ${{ matrix.configuration }} -o ${{ env.SolutionName }}-${{ matrix.configuration }}

      - name: Get version from DLL
        id: extract-version
        run: |
          version=$(dotnet ./StayInTarkov-${{ matrix.configuration }}/StayInTarkov.dll --version)
          echo "::set-output name=VERSION::$version"

      - name: Remove unnecessary files
        run: |
          rm ${{ env.SolutionName }}-${{ matrix.configuration }}/StayInTarkov.pdb

      - name: Zip remaining files
        run: |
          zip -r ${{ env.SolutionName }}-${{ matrix.configuration }}.zip ${{ env.SolutionName }}-${{ matrix.configuration }}

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: StayInTarkov-${{ matrix.configuration }}-${{ steps.extract-version.outputs.VERSION }}
          path: ${{ env.SolutionName }}-${{ matrix.configuration }}/
          if-no-files-found: error

      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: ${{ matrix.configuration == 'Release' }}
        with:
          draft: true
          generate_release_notes: true
          files: ${{ env.SolutionName }}-${{ matrix.configuration }}.zip
          tag_name: StayInTarkov.Client-${{ steps.extract-version.outputs.VERSION }}
